language: csharp
mono: none
dist: xenial
dotnet: 3.1
sudo: required
script:
  - dotnet restore ./Vaughan
  - dotnet restore ./VaughanTests
  - dotnet build -c Release
  - dotnet test -c Release ./VaughanTests
  #- dotnet pack -o . /p:Version=0.4.0.$TRAVIS_BUILD_NUMBER-alpha
  #- if [ "$TRAVIS_BRANCH" != "master" ]; then travis_terminate $TRAVIS_TEST_RESULT; fi;
  #- dotnet nuget push ./Vaughan/Vaughan.*.nupkg -k $NugetApiKey -s https://www.nuget.org/
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
