version: 0.0.{build}
image: Visual Studio 2017
install:
    - ps: >-
        ./build/install-dotnet.ps1
        dotnet --version
before_build:
    - cmd: >-
        dotnet restore
build_script:
    - cmd: >-
        dotnet build
test_script:
    - cmd: >-
        dotnet test ./VaughanTests
